.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MAKE-JPKG 1 "January 22, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
make-jpkg \- builds Debian packages from Java binary distributions
.SH SYNOPSIS
.B make-jpkg
[\fIOPTION\fR]... [\fIFILE\fR]
.SH DESCRIPTION
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.PP
\fBmake-jpkg\fP builds a Debian package from the given Java
distribution FILE.
.PP
Supported java binary distributions currently include:
  * Oracle (http://www.oracle.com/technetwork/java/javase/downloads) :
    - The Java Development Kit (JDK), version 6, 7 and 8
    - The Java Runtime Environment (JRE), version 6, 7 and 8
    - The Java API Javadoc, version 6, 7 and 8
  (Choose tar.gz archives or self-extracting archives, do _not_ choose the RPM!)
.PP
The following options are recognized:
.TP
.B --full-name \fINAME\fR
full name used in the maintainer field of the package
.TP
.B --email \fIEMAIL\fR
email address used in the maintainer field of the package
.TP
.B --distribution \fIDISTRIBUTION\fR
distribution to use in the debian changelog for the resulting package
.TP
.B --changes
create a .changes file
.TP
.B --revision
add debian revision
.TP
.B --source
build a source package instead of a binary deb package
.TP
.B --with-system-certs
Replace the JVMs keystore with a softlink to the system's keystore,
(/etc/ssl/certs/java/cacerts) which is managed automatically by the
ca-certificates and ca-certificates-java packages.
.TP
.B --help
display help text and exit
.TP
.B --version
output version information and exit
.PP
Download a supported JRE, JDK, API tar.gz or self-extracting archive from
.B http://www.oracle.com/technetwork/java/javase/downloads
and execute
.B make-jpkg
.I file
with the downloaded file. The program asks the user for additional
information and builds a Debian binary package in the current
directory.
.PP
The program requires about 200 MB free disk space in a temporary
directory. The temporary directory defaults to
.I /tmp
but you can specify an alternate directory by setting the environment
variable \fITMPDIR\fR.
.SH EXAMPLE
To install Oracle(TM) 7 Standard Edition JDK, download a release - 64 bits version of update 2 from http://www.oracle.com/technetwork/java/javase/downloads/jdk-7u2-download-1377129.html in this example - and invoke make-jpkg:
.IP
make-jpkg <path_to_download_directory>/jdk-7u2-linux-x64.tar.gz
.PP
This generate a Debian package in the current directory, that can be installed using dpkg:
.IP
dpkg \-i oracle-java7-jdk_7u2_amd64.deb
.PP
When you're done, you can delete initial download as well as generated package:
.IP
rm <path_to_download_directory>/jdk-7u2-linux-x64.tar.gz oracle-java7-jdk_7u2_amd64.deb
.PP
.SH ENVIRONMENT
.TP
.SM TMPDIR
base directory used for temporary files (defaults to /tmp)
.TP
.SM J2SE_PACKAGE_FULL_NAME
full name used in the maintainer field of the package; if none is supplied
then the default of "Debian Java Maintainers" is used.
.TP
.SM J2SE_PACKAGE_EMAIL
email address used in the maintainer field of the package; if none is supplied
the default of "pkg-java-maintainers@lists.alioth.debian.org" is used.
.SH SEE ALSO
.BR update-java-alternatives(1)
.SH AUTHOR
This manual page was written by Hubert Schmid <j2se-package@z42.de>.

It is now maintained by the Debian Java Maintainers <pkg-java-maintainers@lists.alioth.debian.org>.
